Added commands to allow admins to view/teleport to other player's homes.
FTBTeam/FTB-Essentials pull request #31
Opened 2021-12-21 13:02 UTC by Sintinium

Added admin commands /homefor and /listhomesfor to allow teleporting and viewing other player's homes.

Examples:
`/homefor steve home1` Teleports you to steve's home1.
`/homefor steve` Shows a list of steve's homes.
`/listhomesfor steve` Shows a list of steve's homes.

2022-01-15 13:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FTBTeam/FTB-Essentials?pullRequest=31) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FTBTeam/FTB-Essentials?pullRequest=31) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FTBTeam/FTB-Essentials?pullRequest=31) it.</sub>

2022-04-03 12:26 UTC, MaxNeedsSnacks commented
Apologies for the long wait, I was waiting on a review from Lat originally, but I'll get to checking this PR out myself soon ^^

2022-04-03 12:45 UTC, MichaelHillcox requested changes
Please ensure this works against the 1.18/dev branch. I've changed your targetting banch but can not verify that it works.

2023-03-28 08:18 UTC, desht commented
@Sintinium are you still interested in getting this PR pulled?  The change itself looks good.

2024-09-07 11:45 UTC, lITronusIl commented
> Added admin commands /homefor and /listhomesfor to allow teleporting and viewing other player's homes. This also has offline support so admins can view offline player's homes too.
> 
> Examples: `/homefor steve home1` Teleports you to steve's home1. `/homefor steve` Shows a list of steve's homes. `/listhomesfor steve` Shows a list of steve's homes.

hey, playing on 1.21.1 rn and cant use this, playing on a fabric server with op level 4. did u remove it?

2024-09-09 09:14 UTC, desht commented
> did u remove it?

No, it was never added, because the creator of the PR hasn't responded to requests to update to modern versions of Minecraft.

2026-04-05 08:56 UTC, MichaelHillcox commented
Closing due to inactivity

2026-04-05 08:56 UTC, closed without merging